### ISSUE TITLE
output files lost if terminal connection is lost

### ISSUE THREAD

**Issue by bcolloran** [mozilla/jydoop#36]
I discovered this problem b/c of the flaky wi-fi in the SF office... if my connection to e.g. the Mango cluster is lost, my jobs will complete without issue, but the target output file will not be written.

'Screen' can be used to work-around, but I wonder if it's possible to have jydoop write its output independent of an active shell (or whatevs.)

**Comment by bsmedberg** [comment]
Use nohup... the problem is that we're receiving SIGHUP and dealing with that in Java is hard.
