### ISSUE TITLE
doc request:  what are the 'ARGS' and how are they implemented?

### ISSUE THREAD

**Issue by gregglind** [mozilla/jydoop#49]
In partcular:

```
make hadoop ARGS="scripts/osdistribution.py outputfile 20130330 20130330"
```

How do the two date arguments work?

**Comment by bsmedberg** [comment]
The args are parsed by the setupjob script https://github.com/mozilla/jydoop/blob/master/pylib/telemetryutils.py#L65 and turned into hbase query ranges. Although this is telemetry stuff, which doesn't need/use jydoop any more: http://mreid-moz.github.io/blog/2013/11/06/current-state-of-telemetry-analysis/

**Comment by gregglind** [comment]
Maybe change the README then, where there are lots of magical looking things peeking through.
